export const countrys = () => {
  return [
    { UlkeAdi: "TÜRKİYE", UlkeKodu: "TR", icon: "tr" },
    { UlkeAdi: "KORE", UlkeKodu: "KR", icon: "kr" },
    { UlkeAdi: "JAPONYA", UlkeKodu: "JP", icon: "jp" },
    { UlkeAdi: "HİNDİSTAN", UlkeKodu: "IN", icon: "in" },
    { UlkeAdi: "İSVİÇRE", UlkeKodu: "CH", icon: "ch" },
    { UlkeAdi: "İNGİLTERE", UlkeKodu: "GB", icon: "gb" },
    { UlkeAdi: "AMERİKA", UlkeKodu: "US", icon: "us" },
    { UlkeAdi: "A.B.D.", UlkeKodu: "US", icon: "us" },
    { UlkeAdi: "ALMANYA", UlkeKodu: "DE", icon: "de" },
    { UlkeAdi: "İSPANYA", UlkeKodu: "ES", icon: "es" },
    { UlkeAdi: "İTALYA", UlkeKodu: "IT", icon: "it" },
    { UlkeAdi: "FRANSA", UlkeKodu: "FR", icon: "fr" },
    { UlkeAdi: "MISIR", UlkeKodu: "EG", icon: "eg" },
    { UlkeAdi: "TAYVAN", UlkeKodu: "TW", icon: "tw" },
    { UlkeAdi: "ENDONEZYA", UlkeKodu: "ID", icon: "id" },
    { UlkeAdi: "KUZEY KIBRIS TÜRK CUMHURİYETİ", UlkeKodu: "CY", icon: "cy" },
    { UlkeAdi: "POLONYA", UlkeKodu: "PL", icon: "pl" },
    { UlkeAdi: "GÜRCİSTAN", UlkeKodu: "GE", icon: "ge" },
    { UlkeAdi: "KKTC", UlkeKodu: "CY", icon: "cy" },
    { UlkeAdi: "ARNAVUTLUK", UlkeKodu: "AL", icon: "al" },
    { UlkeAdi: "İSVEÇ", UlkeKodu: "SE", icon: "se" },
    { UlkeAdi: "HOLLANDA", UlkeKodu: "NL", icon: "nl" },
    { UlkeAdi: "AVUSTURYA", UlkeKodu: "AT", icon: "at" },
    { UlkeAdi: "SLOVENYA", UlkeKodu: "SI", icon: "si" },
    { UlkeAdi: "BELÇİKA", UlkeKodu: "BE", icon: "be" },
    { UlkeAdi: "YUNANİSTAN", UlkeKodu: "GR", icon: "gr" },
    { UlkeAdi: "ETİYOPYA", UlkeKodu: "ET", icon: "et" },
    { UlkeAdi: "KUVEYT", UlkeKodu: "KW", icon: "kw" },
    { UlkeAdi: "RUSYA", UlkeKodu: "RU", icon: "ru" },
    { UlkeAdi: "NORVEÇ", UlkeKodu: "NO", icon: "no" },
    { UlkeAdi: "MACARİSTAN", UlkeKodu: "HU", icon: "hu" },
    { UlkeAdi: "HIRVATİSTAN", UlkeKodu: "HR", icon: "hr" },
    { UlkeAdi: "ROMANYA", UlkeKodu: "RO", icon: "ro" },
    { UlkeAdi: "LİTVANYA", UlkeKodu: "LT", icon: "lt" },
    { UlkeAdi: "BULGARİSTAN", UlkeKodu: "BG", icon: "bg" },
    { UlkeAdi: "DANİMARKA", UlkeKodu: "DK", icon: "dk" },
    { UlkeAdi: "İRLANDA", UlkeKodu: "IE", icon: "ie" },
    { UlkeAdi: "GÜNEY AFRİKA", UlkeKodu: "ZA", icon: "za" },
    { UlkeAdi: "ÇEK CUMHURİYETİ", UlkeKodu: "CZ", icon: "cz" },
    { UlkeAdi: "ÇİN HALK CUMHURİYETİ", UlkeKodu: "CN", icon: "cn" },
    { UlkeAdi: "İRAN", UlkeKodu: "IR", icon: "ir" },
    { UlkeAdi: "MALTA", UlkeKodu: "MT", icon: "mt" },
    { UlkeAdi: "PORTEKİZ", UlkeKodu: "PT", icon: "pt" },
    { UlkeAdi: "ŞİLİ", UlkeKodu: "CL", icon: "cl" },
    { UlkeAdi: "KOSOVA", UlkeKodu: "XK", icon: "xk" },
    { UlkeAdi: "MOLDOVA", UlkeKodu: "MD", icon: "md" },
    { UlkeAdi: "AVUSTRALYA", UlkeKodu: "AU", icon: "au" },
    { UlkeAdi: "UKRAYNA", UlkeKodu: "UA", icon: "ua" },
    { UlkeAdi: "MALEZYA", UlkeKodu: "MY", icon: "my" },
    { UlkeAdi: "FİNLANDİYA", UlkeKodu: "FI", icon: "fi" },
    { UlkeAdi: "TAYLAND", UlkeKodu: "TH", icon: "th" },
    { UlkeAdi: "İSRAİL", UlkeKodu: "IL", icon: "il" },
    { UlkeAdi: "KOLOMBİYA", UlkeKodu: "CO", icon: "co" },
    { UlkeAdi: "YENİ ZELANDA", UlkeKodu: "NZ", icon: "nz" },
    { UlkeAdi: "HONG KONG", UlkeKodu: "HK", icon: "hk" },
    { UlkeAdi: "SİNGAPUR", UlkeKodu: "SG", icon: "sg" },
    { UlkeAdi: "GÜNEY KORE", UlkeKodu: "KR", icon: "kr" },
    { UlkeAdi: "SURİYE", UlkeKodu: "SY", icon: "sy" },
    { UlkeAdi: "ÜRDÜN", UlkeKodu: "JO", icon: "jo" },
    { UlkeAdi: "KAZAKİSTAN", UlkeKodu: "KZ", icon: "kz" },
    { UlkeAdi: "TUNUS", UlkeKodu: "TN", icon: "tn" },
    { UlkeAdi: "BAHREYN", UlkeKodu: "BH", icon: "bh" },
    { UlkeAdi: "LÜBNAN", UlkeKodu: "LB", icon: "lb" },
    { UlkeAdi: "KANADA", UlkeKodu: "CA", icon: "ca" },
    { UlkeAdi: "MEKSİKA", UlkeKodu: "MX", icon: "mx" },
    { UlkeAdi: "KÜBA", UlkeKodu: "CU", icon: "cu" },
    { UlkeAdi: "BREZİLYA", UlkeKodu: "BR", icon: "br" },
    { UlkeAdi: "EKVATOR", UlkeKodu: "EC", icon: "ec" },
    { UlkeAdi: "SUUDİ ARABİSTAN", UlkeKodu: "SA", icon: "sa" },
    { UlkeAdi: "BAE", UlkeKodu: "AE", icon: "ae" },
    { UlkeAdi: "MOZAMBİK", UlkeKodu: "MZ", icon: "mz" },
    { UlkeAdi: "BOSNA HERSEK", UlkeKodu: "BA", icon: "ba" },
    { UlkeAdi: "KATAR", UlkeKodu: "QA", icon: "qa" },
    { UlkeAdi: "UGANDA", UlkeKodu: "UG", icon: "ug" },
    { UlkeAdi: "SENEGAL", UlkeKodu: "SN", icon: "sn" },
    { UlkeAdi: "KENYA", UlkeKodu: "KE", icon: "ke" },
    { UlkeAdi: "LİBYA", UlkeKodu: "LY", icon: "ly" },
    { UlkeAdi: "FAS", UlkeKodu: "MA", icon: "ma" },
    { UlkeAdi: "CEZAYİR", UlkeKodu: "DZ", icon: "dz" },
    { UlkeAdi: "TANZANYA", UlkeKodu: "TZ", icon: "tz" },
    { UlkeAdi: "GANA", UlkeKodu: "GH", icon: "gh" },
    { UlkeAdi: "PAKİSTAN", UlkeKodu: "PK", icon: "pk" },
    { UlkeAdi: "TÜRKMENİSTAN", UlkeKodu: "TM", icon: "tm" },
    { UlkeAdi: "BANGLADEŞ", UlkeKodu: "BD", icon: "bd" },
    { UlkeAdi: "İZLANDA", UlkeKodu: "IS", icon: "is" },
    { UlkeAdi: "PANAMA", UlkeKodu: "PA", icon: "pa" },
    { UlkeAdi: "ERMENİSTAN", UlkeKodu: "AM", icon: "am" },
    { UlkeAdi: "BELARUS", UlkeKodu: "BY", icon: "by" },
    { UlkeAdi: "ESTONYA", UlkeKodu: "EE", icon: "ee" },
    { UlkeAdi: "SLOVAKYA", UlkeKodu: "SK", icon: "sk" },
  ];
};

export const PhoneCountries = [
  { label: 'Türkiye (+90)', value: 'TR', areaCode: '90', icon: 'tr' },
  { label: 'Kore (+82)', value: 'KR', areaCode: '82', icon: 'kr' },
  { label: 'Japonya (+81)', value: 'JP', areaCode: '81', icon: 'jp' },
  { label: 'Hindistan (+91)', value: 'IN', areaCode: '91', icon: 'in' },
  { label: 'İsviçre (+41)', value: 'CH', areaCode: '41', icon: 'ch' },
  { label: 'İngiltere (+44)', value: 'GB', areaCode: '44', icon: 'gb' },
  { label: 'Amerika (+1)', value: 'US', areaCode: '1', icon: 'us' },
  { label: 'Almanya (+49)', value: 'DE', areaCode: '49', icon: 'de' },
  { label: 'İspanya (+34)', value: 'ES', areaCode: '34', icon: 'es' },
  { label: 'İtalya (+39)', value: 'IT', areaCode: '39', icon: 'it' },
  { label: 'Fransa (+33)', value: 'FR', areaCode: '33', icon: 'fr' },
  { label: 'Mısır (+20)', value: 'EG', areaCode: '20', icon: 'eg' },
  { label: 'Tayvan (+886)', value: 'TW', areaCode: '886', icon: 'tw' },
  { label: 'Endonezya (+62)', value: 'ID', areaCode: '62', icon: 'id' },
  { label: 'Kuzey Kıbrıs Türk Cumhuriyeti (+90)', value: 'CY', areaCode: '90', icon: 'cy' },
  { label: 'Polonya (+48)', value: 'PL', areaCode: '48', icon: 'pl' },
  { label: 'Gürcistan (+995)', value: 'GE', areaCode: '995', icon: 'ge' },
  { label: 'KKTC (+90)', value: 'CY', areaCode: '90', icon: 'cy' },
  { label: 'Arnavutluk (+355)', value: 'AL', areaCode: '355', icon: 'al' },
  { label: 'İsveç (+46)', value: 'SE', areaCode: '46', icon: 'se' },
  { label: 'Hollanda (+31)', value: 'NL', areaCode: '31', icon: 'nl' },
  { label: 'Avusturya (+43)', value: 'AT', areaCode: '43', icon: 'at' },
  { label: 'Slovenya (+386)', value: 'SI', areaCode: '386', icon: 'si' },
  { label: 'Belçika (+32)', value: 'BE', areaCode: '32', icon: 'be' },
  { label: 'Yunanistan (+30)', value: 'GR', areaCode: '30', icon: 'gr' },
  { label: 'Etiyopya (+251)', value: 'ET', areaCode: '251', icon: 'et' },
  { label: 'Kuveyt (+965)', value: 'KW', areaCode: '965', icon: 'kw' },
  { label: 'Rusya (+7)', value: 'RU', areaCode: '7', icon: 'ru' },
  { label: 'Norveç (+47)', value: 'NO', areaCode: '47', icon: 'no' },
  { label: 'Macaristan (+36)', value: 'HU', areaCode: '36', icon: 'hu' },
  { label: 'Hırvatistan (+385)', value: 'HR', areaCode: '385', icon: 'hr' },
  { label: 'Romanya (+40)', value: 'RO', areaCode: '40', icon: 'ro' },
  { label: 'Litvanya (+370)', value: 'LT', areaCode: '370', icon: 'lt' },
  { label: 'Bulgaristan (+359)', value: 'BG', areaCode: '359', icon: 'bg' },
  { label: 'Danimarka (+45)', value: 'DK', areaCode: '45', icon: 'dk' },
  { label: 'İrlanda (+353)', value: 'IE', areaCode: '353', icon: 'ie' },
  { label: 'Güney Afrika (+27)', value: 'ZA', areaCode: '27', icon: 'za' },
  { label: 'Çek Cumhuriyeti (+420)', value: 'CZ', areaCode: '420', icon: 'cz' },
  { label: 'Çin Halk Cumhuriyeti (+86)', value: 'CN', areaCode: '86', icon: 'cn' },
  { label: 'İran (+98)', value: 'IR', areaCode: '98', icon: 'ir' },
  { label: 'Malta (+356)', value: 'MT', areaCode: '356', icon: 'mt' },
  { label: 'Portekiz (+351)', value: 'PT', areaCode: '351', icon: 'pt' },
  { label: 'Şili (+56)', value: 'CL', areaCode: '56', icon: 'cl' },
  { label: 'Kosova (+383)', value: 'XK', areaCode: '383', icon: 'xk' },
  { label: 'Moldova (+373)', value: 'MD', areaCode: '373', icon: 'md' },
  { label: 'Avustralya (+61)', value: 'AU', areaCode: '61', icon: 'au' },
  { label: 'Ukrayna (+380)', value: 'UA', areaCode: '380', icon: 'ua' },
  { label: 'Malezya (+60)', value: 'MY', areaCode: '60', icon: 'my' },
  { label: 'Finlandiya (+358)', value: 'FI', areaCode: '358', icon: 'fi' },
  { label: 'Tayland (+66)', value: 'TH', areaCode: '66', icon: 'th' },
  { label: 'İsrail (+972)', value: 'IL', areaCode: '972', icon: 'il' },
  { label: 'Kolombiya (+57)', value: 'CO', areaCode: '57', icon: 'co' },
  { label: 'Yeni Zelanda (+64)', value: 'NZ', areaCode: '64', icon: 'nz' },
  { label: 'Hong Kong (+852)', value: 'HK', areaCode: '852', icon: 'hk' },
  { label: 'Singapur (+65)', value: 'SG', areaCode: '65', icon: 'sg' },
  { label: 'Güney Kore (+82)', value: 'KR', areaCode: '82', icon: 'kr' },
  { label: 'Suriye (+963)', value: 'SY', areaCode: '963', icon: 'sy' },
  { label: 'Ürdün (+962)', value: 'JO', areaCode: '962', icon: 'jo' },
  { label: 'Kazakistan (+7)', value: 'KZ', areaCode: '7', icon: 'kz' },
  { label: 'Tunus (+216)', value: 'TN', areaCode: '216', icon: 'tn' },
  { label: 'Bahreyn (+973)', value: 'BH', areaCode: '973', icon: 'bh' },
  { label: 'Lübnan (+961)', value: 'LB', areaCode: '961', icon: 'lb' },
  { label: 'Kanada (+1)', value: 'CA', areaCode: '1', icon: 'ca' },
  { label: 'Meksika (+52)', value: 'MX', areaCode: '52', icon: 'mx' },
  { label: 'Küba (+53)', value: 'CU', areaCode: '53', icon: 'cu' },
  { label: 'Brezilya (+55)', value: 'BR', areaCode: '55', icon: 'br' },
  { label: 'Ekvator (+593)', value: 'EC', areaCode: '593', icon: 'ec' },
  { label: 'Suudi Arabistan (+966)', value: 'SA', areaCode: '966', icon: 'sa' },
  { label: 'BAE (+971)', value: 'AE', areaCode: '971', icon: 'ae' },
  { label: 'Mozambik (+258)', value: 'MZ', areaCode: '258', icon: 'mz' },
  { label: 'Bosna Hersek (+387)', value: 'BA', areaCode: '387', icon: 'ba' },
  { label: 'Katar (+974)', value: 'QA', areaCode: '974', icon: 'qa' },
  { label: 'Uganda (+256)', value: 'UG', areaCode: '256', icon: 'ug' },
  { label: 'Senegal (+221)', value: 'SN', areaCode: '221', icon: 'sn' },
  { label: 'Kenya (+254)', value: 'KE', areaCode: '254', icon: 'ke' },
  { label: 'Libya (+218)', value: 'LY', areaCode: '218', icon: 'ly' },
  { label: 'Fas (+212)', value: 'MA', areaCode: '212', icon: 'ma' },
  { label: 'Cezayir (+213)', value: 'DZ', areaCode: '213', icon: 'dz' },
  { label: 'Tanzanya (+255)', value: 'TZ', areaCode: '255', icon: 'tz' },
  { label: 'Gana (+233)', value: 'GH', areaCode: '233', icon: 'gh' },
  { label: 'Pakistan (+92)', value: 'PK', areaCode: '92', icon: 'pk' },
  { label: 'Türkmenistan (+993)', value: 'TM', areaCode: '993', icon: 'tm' },
  { label: 'Bangladeş (+880)', value: 'BD', areaCode: '880', icon: 'bd' },
  { label: 'İzlanda (+354)', value: 'IS', areaCode: '354', icon: 'is' },
  { label: 'Panama (+507)', value: 'PA', areaCode: '507', icon: 'pa' },
  { label: 'Ermenistan (+374)', value: 'AM', areaCode: '374', icon: 'am' },
  { label: 'Belarus (+375)', value: 'BY', areaCode: '375', icon: 'by' },
  { label: 'Estonya (+372)', value: 'EE', areaCode: '372', icon: 'ee' },
  { label: 'Slovakya (+421)', value: 'SK', areaCode: '421', icon: 'sk' },
];


export const PhoneCountriesAndRegex = [
  { label: 'Türkiye (+90)', value: 'TR', areaCode: '90', icon: 'tr', regex: /^(\+90\s)?\d{3}(\s\d{3}){2}\d{2}$/ },
  { label: 'Kore (+82)', value: 'KR', areaCode: '82', icon: 'kr', regex: /^(\+82\s)?\d{2,3}-\d{3,4}-\d{4}$/ },
  { label: 'Japonya (+81)', value: 'JP', areaCode: '81', icon: 'jp', regex: /^(\+81\s)?\d{1,4}-\d{1,4}-\d{1,4}$/ },
  { label: 'Hindistan (+91)', value: 'IN', areaCode: '91', icon: 'in', regex: /^(\+91\s)?\d{4,5}-\d{5,6}$/ },
  { label: 'İsviçre (+41)', value: 'CH', areaCode: '41', icon: 'ch', regex: /^(\+41\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'İngiltere (+44)', value: 'GB', areaCode: '44', icon: 'gb', regex: /^(\+44\s)?\d{4}\s\d{4}\s\d{4}$/ },
  { label: 'Amerika (+1)', value: 'US', areaCode: '1', icon: 'us', regex: /^(\+1\s)?\(\d{3}\)\s\d{3}-\d{4}$/ },
  { label: 'Almanya (+49)', value: 'DE', areaCode: '49', icon: 'de', regex: /^(\+49\s)?\d{4,5}-\d{4,5}$/ },
  { label: 'İspanya (+34)', value: 'ES', areaCode: '34', icon: 'es', regex: /^(\+34\s)?\d{3}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'İtalya (+39)', value: 'IT', areaCode: '39', icon: 'it', regex: /^(\+39\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Fransa (+33)', value: 'FR', areaCode: '33', icon: 'fr', regex: /^(\+33\s)?\d{1}\s\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Mısır (+20)', value: 'EG', areaCode: '20', icon: 'eg', regex: /^(\+20\s)?\d{2,3}-\d{2,4}-\d{4}$/ },
  { label: 'Tayvan (+886)', value: 'TW', areaCode: '886', icon: 'tw', regex: /^(\+886\s)?\d{2,3}-\d{2,3}-\d{3,4}$/ },
  { label: 'Endonezya (+62)', value: 'ID', areaCode: '62', icon: 'id', regex: /^(\+62\s)?\d{2,3}-\d{3,4}-\d{4}$/ },
  { label: 'Kuzey Kıbrıs Türk Cumhuriyeti (+90)', value: 'CY', areaCode: '90', icon: 'cy', regex: /^(\+90\s)?\d{2}\s\d{3}\s\d{2}\d{2}$/ },
  { label: 'Polonya (+48)', value: 'PL', areaCode: '48', icon: 'pl', regex: /^(\+48\s)?\d{3}-\d{3}-\d{3}$/ },
  { label: 'Gürcistan (+995)', value: 'GE', areaCode: '995', icon: 'ge', regex: /^(\+995\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'KKTC (+90)', value: 'CY', areaCode: '90', icon: 'cy', regex: /^(\+90\s)?\d{2}\s\d{3}\s\d{2}\d{2}$/ },
  { label: 'Arnavutluk (+355)', value: 'AL', areaCode: '355', icon: 'al', regex: /^(\+355\s)?\d{2}-\d{3}-\d{4}$/ },
  { label: 'İsveç (+46)', value: 'SE', areaCode: '46', icon: 'se', regex: /^(\+46\s)?\d{2}-\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Hollanda (+31)', value: 'NL', areaCode: '31', icon: 'nl', regex: /^(\+31\s)?\d{1,3}-\d{4}\s\d{3}$/ },
  { label: 'Avusturya (+43)', value: 'AT', areaCode: '43', icon: 'at', regex: /^(\+43\s)?\d{1,4}-\d{4}$/ },
  { label: 'Slovenya (+386)', value: 'SI', areaCode: '386', icon: 'si', regex: /^(\+386\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Belçika (+32)', value: 'BE', areaCode: '32', icon: 'be', regex: /^(\+32\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Yunanistan (+30)', value: 'GR', areaCode: '30', icon: 'gr', regex: /^(\+30\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Etiyopya (+251)', value: 'ET', areaCode: '251', icon: 'et', regex: /^(\+251\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Kuveyt (+965)', value: 'KW', areaCode: '965', icon: 'kw', regex: /^(\+965\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Rusya (+7)', value: 'RU', areaCode: '7', icon: 'ru', regex: /^(\+7\s)?\d{3}-\d{3}-\d{2}-\d{2}$/ },
  { label: 'Norveç (+47)', value: 'NO', areaCode: '47', icon: 'no', regex: /^(\+47\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Macaristan (+36)', value: 'HU', areaCode: '36', icon: 'hu', regex: /^(\+36\s)?\d{2}-\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Hırvatistan (+385)', value: 'HR', areaCode: '385', icon: 'hr', regex: /^(\+385\s)?\d{2}-\d{3}-\d{3}$/ },
  { label: 'Romanya (+40)', value: 'RO', areaCode: '40', icon: 'ro', regex: /^(\+40\s)?\d{2}-\d{3}-\d{3}$/ },
  { label: 'Litvanya (+370)', value: 'LT', areaCode: '370', icon: 'lt', regex: /^(\+370\s)?\d{2}-\d{3}-\d{3}$/ },
  { label: 'Bulgaristan (+359)', value: 'BG', areaCode: '359', icon: 'bg', regex: /^(\+359\s)?\d{2}-\d{3}-\d{3}$/ },
  { label: 'Danimarka (+45)', value: 'DK', areaCode: '45', icon: 'dk', regex: /^(\+45\s)?\d{2}-\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'İrlanda (+353)', value: 'IE', areaCode: '353', icon: 'ie', regex: /^(\+353\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Güney Afrika (+27)', value: 'ZA', areaCode: '27', icon: 'za', regex: /^(\+27\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Çek Cumhuriyeti (+420)', value: 'CZ', areaCode: '420', icon: 'cz', regex: /^(\+420\s)?\d{3}\s\d{3}\s\d{3}$/ },
  { label: 'Çin Halk Cumhuriyeti (+86)', value: 'CN', areaCode: '86', icon: 'cn', regex: /^(\+86\s)?\d{2,4}-\d{4}-\d{4}$/ },
  { label: 'İran (+98)', value: 'IR', areaCode: '98', icon: 'ir', regex: /^(\+98\s)?\d{2,3}\s\d{3,4}-\d{4}$/ },
  { label: 'Malta (+356)', value: 'MT', areaCode: '356', icon: 'mt', regex: /^(\+356\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Portekiz (+351)', value: 'PT', areaCode: '351', icon: 'pt', regex: /^(\+351\s)?\d{2}\s\d{3}\s\d{3}\s\d{3}$/ },
  { label: 'Şili (+56)', value: 'CL', areaCode: '56', icon: 'cl', regex: /^(\+56\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Kosova (+383)', value: 'XK', areaCode: '383', icon: 'xk', regex: /^(\+383\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Moldova (+373)', value: 'MD', areaCode: '373', icon: 'md', regex: /^(\+373\s)?\d{2}\s\d{2}\s\d{3}$/ },
  { label: 'Avustralya (+61)', value: 'AU', areaCode: '61', icon: 'au', regex: /^(\+61\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Ukrayna (+380)', value: 'UA', areaCode: '380', icon: 'ua', regex: /^(\+380\s)?\d{3}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Malezya (+60)', value: 'MY', areaCode: '60', icon: 'my', regex: /^(\+60\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Finlandiya (+358)', value: 'FI', areaCode: '358', icon: 'fi', regex: /^(\+358\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Tayland (+66)', value: 'TH', areaCode: '66', icon: 'th', regex: /^(\+66\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'İsrail (+972)', value: 'IL', areaCode: '972', icon: 'il', regex: /^(\+972\s)?\d{2}\s\d{3}\s\d{4}$/ },
  { label: 'Kolombiya (+57)', value: 'CO', areaCode: '57', icon: 'co', regex: /^(\+57\s)?\d{2}\s\d{3}\s\d{4}$/ },
  { label: 'Yeni Zelanda (+64)', value: 'NZ', areaCode: '64', icon: 'nz', regex: /^(\+64\s)?\d{2}\s\d{3}\s\d{3}\s\d{4}$/ },
  { label: 'Hong Kong (+852)', value: 'HK', areaCode: '852', icon: 'hk', regex: /^(\+852\s)?\d{4}\s\d{4}$/ },
  { label: 'Singapur (+65)', value: 'SG', areaCode: '65', icon: 'sg', regex: /^(\+65\s)?\d{4}\s\d{4}$/ },
  { label: 'Güney Kore (+82)', value: 'KR', areaCode: '82', icon: 'kr', regex: /^(\+82\s)?\d{2,3}-\d{3,4}-\d{4}$/ },
  { label: 'Suriye (+963)', value: 'SY', areaCode: '963', icon: 'sy', regex: /^(\+963\s)?\d{1,3}\s\d{3}\s\d{3}$/ },
  { label: 'Ürdün (+962)', value: 'JO', areaCode: '962', icon: 'jo', regex: /^(\+962\s)?\d{1,3}-\d{4}-\d{4}$/ },
  { label: 'Kazakistan (+7)', value: 'KZ', areaCode: '7', icon: 'kz', regex: /^(\+7\s)?\d{3}-\d{3}-\d{4}$/ },
  { label: 'Tunus (+216)', value: 'TN', areaCode: '216', icon: 'tn', regex: /^(\+216\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Bahreyn (+973)', value: 'BH', areaCode: '973', icon: 'bh', regex: /^(\+973\s)?\d{3}\s\d{3}$/ },
  { label: 'Lübnan (+961)', value: 'LB', areaCode: '961', icon: 'lb', regex: /^(\+961\s)?\d{1,3}-\d{3}-\d{3}$/ },
  { label: 'Kanada (+1)', value: 'CA', areaCode: '1', icon: 'ca', regex: /^(\+1\s)?\(\d{3}\)\s\d{3}-\d{4}$/ },
  { label: 'Meksika (+52)', value: 'MX', areaCode: '52', icon: 'mx', regex: /^(\+52\s)?\d{1,3}-\d{3}-\d{4}$/ },
  { label: 'Küba (+53)', value: 'CU', areaCode: '53', icon: 'cu', regex: /^(\+53\s)?\d{1,3}-\d{3}-\d{4}$/ },
  { label: 'Brezilya (+55)', value: 'BR', areaCode: '55', icon: 'br', regex: /^(\+55\s)?\d{2}\s\d{4,5}-\d{4}$/ },
  { label: 'Ekvator (+593)', value: 'EC', areaCode: '593', icon: 'ec', regex: /^(\+593\s)?\d{1,4}-\d{3}-\d{4}$/ },
  { label: 'Suudi Arabistan (+966)', value: 'SA', areaCode: '966', icon: 'sa', regex: /^(\+966\s)?\d{2,3}-\d{3}-\d{4}$/ },
  { label: 'BAE (+971)', value: 'AE', areaCode: '971', icon: 'ae', regex: /^(\+971\s)?\d{1,3}-\d{3}-\d{4}$/ },
  { label: 'Mozambik (+258)', value: 'MZ', areaCode: '258', icon: 'mz', regex: /^(\+258\s)?\d{2}\s\d{2,3}\s\d{2,3}\s\d{2}$/ },
  { label: 'Bosna Hersek (+387)', value: 'BA', areaCode: '387', icon: 'ba', regex: /^(\+387\s)?\d{1,3}-\d{3}-\d{3}$/ },
  { label: 'Katar (+974)', value: 'QA', areaCode: '974', icon: 'qa', regex: /^(\+974\s)?\d{2,3}-\d{3}-\d{3}$/ },
  { label: 'Uganda (+256)', value: 'UG', areaCode: '256', icon: 'ug', regex: /^(\+256\s)?\d{1,4}-\d{3}-\d{3}$/ },
  { label: 'Senegal (+221)', value: 'SN', areaCode: '221', icon: 'sn', regex: /^(\+221\s)?\d{2,3}-\d{3}-\d{2}-\d{2}$/ },
  { label: 'Kenya (+254)', value: 'KE', areaCode: '254', icon: 'ke', regex: /^(\+254\s)?\d{1,3}-\d{3}-\d{3}$/ },
  { label: 'Libya (+218)', value: 'LY', areaCode: '218', icon: 'ly', regex: /^(\+218\s)?\d{2,3}-\d{4}-\d{4}$/ },
  { label: 'Fas (+212)', value: 'MA', areaCode: '212', icon: 'ma', regex: /^(\+212\s)?\d{1}\s\d{4}-\d{4}-\d{2}$/ },
  { label: 'Cezayir (+213)', value: 'DZ', areaCode: '213', icon: 'dz', regex: /^(\+213\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Tanzanya (+255)', value: 'TZ', areaCode: '255', icon: 'tz', regex: /^(\+255\s)?\d{2}\s\d{3}\s\d{3}\s\d{3}$/ },
  { label: 'Gana (+233)', value: 'GH', areaCode: '233', icon: 'gh', regex: /^(\+233\s)?\d{1}\s\d{4}-\d{3}-\d{3}$/ },
  { label: 'Pakistan (+92)', value: 'PK', areaCode: '92', icon: 'pk', regex: /^(\+92\s)?\d{2}\s\d{4}-\d{4}$/ },
  { label: 'Türkmenistan (+993)', value: 'TM', areaCode: '993', icon: 'tm', regex: /^(\+993\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Bangladeş (+880)', value: 'BD', areaCode: '880', icon: 'bd', regex: /^(\+880\s)?\d{1,4}-\d{3}-\d{3}$/ },
  { label: 'İzlanda (+354)', value: 'IS', areaCode: '354', icon: 'is', regex: /^(\+354\s)?\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Polinezya (+689)', value: 'PF', areaCode: '689', icon: 'pf', regex: /^(\+689\s)?\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Kosta Rika (+506)', value: 'CR', areaCode: '506', icon: 'cr', regex: /^(\+506\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Güney Sudan (+211)', value: 'SS', areaCode: '211', icon: 'ss', regex: /^(\+211\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Kamboçya (+855)', value: 'KH', areaCode: '855', icon: 'kh', regex: /^(\+855\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Fildişi Sahili (+225)', value: 'CI', areaCode: '225', icon: 'ci', regex: /^(\+225\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Jamaika (+1)', value: 'JM', areaCode: '1', icon: 'jm', regex: /^(\+1\s)?\(\d{3}\)\s\d{3}-\d{4}$/ },
  { label: 'Küveyt (+965)', value: 'KW', areaCode: '965', icon: 'kw', regex: /^(\+965\s)?\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Uruguay (+598)', value: 'UY', areaCode: '598', icon: 'uy', regex: /^(\+598\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Moritanya (+222)', value: 'MR', areaCode: '222', icon: 'mr', regex: /^(\+222\s)?\d{2}\s\d{1}\s\d{2}\s\d{2}$/ },
  { label: 'Myanmar (+95)', value: 'MM', areaCode: '95', icon: 'mm', regex: /^(\+95\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Barbados (+1)', value: 'BB', areaCode: '1', icon: 'bb', regex: /^(\+1\s)?\(\d{3}\)\s\d{3}-\d{4}$/ },
  { label: 'Kırgızistan (+996)', value: 'KG', areaCode: '996', icon: 'kg', regex: /^(\+996\s)?\d{2,3}-\d{2}-\d{2}-\d{2}$/ },
  { label: 'Lesotho (+266)', value: 'LS', areaCode: '266', icon: 'ls', regex: /^(\+266\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Karadağ (+382)', value: 'ME', areaCode: '382', icon: 'me', regex: /^(\+382\s)?\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Namibya (+264)', value: 'NA', areaCode: '264', icon: 'na', regex: /^(\+264\s)?\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Oman (+968)', value: 'OM', areaCode: '968', icon: 'om', regex: /^(\+968\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Filipinler (+63)', value: 'PH', areaCode: '63', icon: 'ph', regex: /^(\+63\s)?\d{2}\s\d{3}\s\d{3}\s\d{4}$/ },
  { label: 'Filistin (+970)', value: 'PS', areaCode: '970', icon: 'ps', regex: /^(\+970\s)?\d{2}\s\d{3}\s\d{4}$/ },
  { label: 'Bahamalar (+1)', value: 'BS', areaCode: '1', icon: 'bs', regex: /^(\+1\s)?\(\d{3}\)\s\d{3}-\d{4}$/ },
  { label: 'Bolivya (+591)', value: 'BO', areaCode: '591', icon: 'bo', regex: /^(\+591\s)?\d{1,4}-\d{4}$/ },
  { label: 'Sırbistan (+381)', value: 'RS', areaCode: '381', icon: 'rs', regex: /^(\+381\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Fiji (+679)', value: 'FJ', areaCode: '679', icon: 'fj', regex: /^(\+679\s)?\d{2}\s\d{3}\s\d{2}\s\d{2}$/ },
  { label: 'Şili (+56)', value: 'CL', areaCode: '56', icon: 'cl', regex: /^(\+56\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Panama (+507)', value: 'PA', areaCode: '507', icon: 'pa', regex: /^(\+507\s)?\d{2}\s\d{2}\s\d{2}\s\d{2}$/ },
  { label: 'Arjantin (+54)', value: 'AR', areaCode: '54', icon: 'ar', regex: /^(\+54\s)?\d{2}\s\d{2}\s\d{4}\s\d{4}$/ },
  { label: 'Kongo Demokratik Cumhuriyeti (+243)', value: 'CD', areaCode: '243', icon: 'cd', regex: /^(\+243\s)?\d{2}\s\d{2}\s\d{3}\s\d{3}$/ },
  { label: 'Şangay (+86)', value: 'SH', areaCode: '86', icon: 'sh', regex: /^(\+86\s)?\d{2,4}-\d{4}-\d{4}$/ },
]
